"""Data tab: the trace that Least Squares Fitting fits against.

Either an uploaded experimental CSV, or synthetic data generated by
perturbing the Simulation tab's current rate constants (passed in via
`sim_state`) with Gaussian noise (gaussian_noise.py) and re-integrating.
Stores the chosen trace in st.session_state["current_data"] (plus
ground-truth params if synthetic) for every later tab to read.
"""

import hashlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st

from gaussian_noise import (
    simulate_1step_noisy,
    simulate_2step_noisy,
    add_measurement_noise,
)


def compute_dataset_key(data_label, data_df):
    """Stable content-based identity for a loaded dataset.

    Used to group Profile Likelihood History entries by the underlying data
    they were run against: regenerating/re-uploading the same trace yields
    the same key, while any change to the actual Mean values yields a new one.
    """
    payload = data_label + "|" + ",".join(f"{v:.10g}" for v in data_df["Mean"].to_numpy(dtype=float))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def render_data_tab(sim_state):
    is_two_step = sim_state["is_two_step"]
    t_end = sim_state["t_end"]
    n_points = sim_state["n_points"]
    I0 = sim_state["I0"]
    X0 = sim_state["X0"]
    M0 = sim_state["M0"]
    B0 = sim_state["B0"]
    u = sim_state["u"]
    k1 = sim_state["k1"]
    k2 = sim_state["k2"]
    km = sim_state["km"]
    kb = sim_state["kb"]
    kd = sim_state["kd"]
    alpha = sim_state["alpha"]

    st.markdown(
        "Provide the fluorescence trace to fit against in the **Least Squares "
        "Fitting** tab. Either upload real experimental data from a trench "
        "intensity CSV, or generate synthetic noisy data by perturbing the "
        "simulation's rate constants with Gaussian noise and re-integrating "
        "the model."
    )

    data_source = st.radio(
        "Data source",
        options=["Upload experimental CSV", "Generate synthetic data from simulation"],
    )

    data = None
    data_label = ""

    if data_source == "Upload experimental CSV":
        st.markdown(
            "Upload a trench intensity CSV (columns: `Slice, Mean, StdDev, Min, Max`) "
            "to plot **Mean intensity vs. Slice**."
        )

        uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

        if uploaded_file is not None:
            try:
                candidate = pd.read_csv(uploaded_file)
            except Exception as e:
                st.error(f"Could not read CSV file: {e}")
            else:
                if "Slice" not in candidate.columns or "Mean" not in candidate.columns:
                    st.error(
                        "CSV must contain 'Slice' and 'Mean' columns. "
                        f"Found columns: {list(candidate.columns)}"
                    )
                else:
                    seconds_per_slice = st.number_input(
                        "Time per slice (seconds)",
                        min_value=0.0, value=60.0, step=1.0, format="%.3f",
                        help="Conversion factor from imaging slice/frame number to time. "
                             "Suggested: 60 seconds per slice (adjust to match your "
                             "acquisition interval).",
                    )
                    candidate["Time"] = candidate["Slice"] * seconds_per_slice
                    data = candidate
                    data_label = uploaded_file.name
        else:
            st.info("Upload a CSV file to see the Mean intensity vs. Slice plot.")

    else:
        st.markdown(
            "Generates a synthetic fluorescence trace using the model and "
            "rate constants currently set in the **Simulation** tab. Two independent "
            "noise sources can be applied: Gaussian noise on the rate "
            "constant(s) themselves (drawn fresh at every simulated time "
            "step, before the model is integrated forward), and/or Gaussian "
            "measurement noise added directly to the resulting Mean "
            "intensity trace (e.g. camera/shot noise). The resulting trace "
            "is then treated like experimental data below."
        )

        if is_two_step:
            noise_col1, noise_col2, noise_col3 = st.columns(3)
            with noise_col1:
                k1_noise_std = st.number_input(
                    "k1 noise std dev", min_value=0.0, value=0.02, step=0.01, format="%.4f",
                    help="Standard deviation of the Gaussian noise added to k1 at each time step.",
                )
            with noise_col2:
                k2_noise_std = st.number_input(
                    "k2 noise std dev", min_value=0.0, value=0.02, step=0.01, format="%.4f",
                    help="Standard deviation of the Gaussian noise added to k2 at each time step.",
                )
            with noise_col3:
                kb_noise_std = st.number_input(
                    "kb noise std dev", min_value=0.0, value=0.005, step=0.001, format="%.4f",
                    help="Standard deviation of the Gaussian noise added to kb at each time step.",
                )
        else:
            noise_col1, noise_col2 = st.columns(2)
            with noise_col1:
                km_noise_std = st.number_input(
                    "km noise std dev", min_value=0.0, value=0.02, step=0.01, format="%.4f",
                    help="Standard deviation of the Gaussian noise added to km at each time step.",
                )
            with noise_col2:
                kb_noise_std = st.number_input(
                    "kb noise std dev", min_value=0.0, value=0.005, step=0.001, format="%.4f",
                    help="Standard deviation of the Gaussian noise added to kb at each time step.",
                )

        measurement_noise_std = st.number_input(
            "Measurement noise std dev (Mean intensity)",
            min_value=0.0, value=0.0, step=0.5,
            help="Standard deviation of independent Gaussian noise added directly "
                 "to the simulated Mean intensity trace (e.g. camera/shot noise), "
                 "on top of any rate-constant noise above. Set to 0 to disable.",
        )

        use_seed = st.checkbox("Fix random seed (reproducible noise)", value=False)
        seed = None
        measurement_seed = None
        if use_seed:
            seed = int(st.number_input("Random seed", min_value=0, value=0, step=1))
            measurement_seed = seed + 1

        generate_button = st.button("Generate Synthetic Data", type="primary")

        if generate_button:
            t_syn = np.linspace(0, t_end, int(n_points))
            with st.spinner("Generating synthetic data..."):
                if is_two_step:
                    params_syn = {"u": u, "k1": k1, "k2": k2, "kb": kb, "kd": kd, "alpha": alpha}
                    _, _, _, _, _, F_syn = simulate_2step_noisy(
                        t_syn, params_syn, I0=I0, X0=X0, M0=M0, B0=B0,
                        k1_std=k1_noise_std, k2_std=k2_noise_std, kb_std=kb_noise_std,
                        seed=seed,
                    )
                else:
                    params_syn = {"u": u, "km": km, "kb": kb, "kd": kd, "alpha": alpha}
                    _, _, _, _, F_syn = simulate_1step_noisy(
                        t_syn, params_syn, I0=I0, M0=M0, B0=B0,
                        km_std=km_noise_std, kb_std=kb_noise_std,
                        seed=seed,
                    )

                F_syn = add_measurement_noise(F_syn, measurement_noise_std, seed=measurement_seed)

            st.session_state["synthetic_data_df"] = pd.DataFrame(
                {"Slice": t_syn, "Mean": F_syn, "Time": t_syn}
            )
            st.session_state["synthetic_params"] = {
                "is_two_step": is_two_step,
                "I0": I0,
                "km": None if is_two_step else km,
                "k1": k1 if is_two_step else None,
                "k2": k2 if is_two_step else None,
                "kb": kb,
                "kd": kd,
                "alpha": alpha,
            }
            st.session_state["noise_params"] = {
                "km_noise_std": None if is_two_step else km_noise_std,
                "k1_noise_std": k1_noise_std if is_two_step else None,
                "k2_noise_std": k2_noise_std if is_two_step else None,
                "kb_noise_std": kb_noise_std,
                "measurement_noise_std": measurement_noise_std,
                "seed": seed,
                "measurement_seed": measurement_seed,
            }

        if "synthetic_data_df" in st.session_state:
            data = st.session_state["synthetic_data_df"]
            data_label = "Synthetic data"
        else:
            st.info("Click **Generate Synthetic Data** to create a synthetic trace.")

    dataset_key = None
    if data is not None:
        fig2, ax2 = plt.subplots(figsize=(9, 5))
        ax2.plot(data["Time"], data["Mean"], marker="o", markersize=3)
        ax2.set_xlabel("Time (sec)")
        ax2.set_ylabel("Mean intensity")
        ax2.set_title(data_label)
        fig2.tight_layout()

        st.pyplot(fig2)
        st.dataframe(data)

        dataset_key = compute_dataset_key(data_label, data)
        is_synthetic_source = data_source == "Generate synthetic data from simulation"
        st.session_state.setdefault("dataset_info", {})[dataset_key] = {
            "label": data_label,
            "synthetic_params": st.session_state.get("synthetic_params") if is_synthetic_source else None,
            "noise_params": st.session_state.get("noise_params") if is_synthetic_source else None,
        }

    st.session_state["current_data"] = data
    st.session_state["current_data_label"] = data_label
    st.session_state["current_data_source"] = data_source
    st.session_state["current_dataset_key"] = dataset_key
